const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  PATCH_SOURCE,
  eligibleForDeterministicFallback,
  writeDeterministicCandidatePatch
} = require('../../src/ralph/deterministic-candidate-patch-fallback');

function tmpRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'ralph-deterministic-fallback-'));
}

function story(overrides = {}) {
  return {
    story_id: 'STORY-FALLBACK',
    title: 'Add deterministic fallback smoke note',
    requirement: 'Create a small bounded markdown note for fallback validation.',
    requested_paths: ['docs/fallback-smoke.md'],
    risk: { score: 0, category: 'low', label: 'RISK_0_LOW' },
    ...overrides
  };
}

test('eligibleForDeterministicFallback allows low-risk new docs path on provider rate limit', () => {
  const rootDir = tmpRoot();
  const result = eligibleForDeterministicFallback({
    rootDir,
    story: story(),
    failure_reason: 'provider_rate_limited'
  });

  expect(result).toMatchObject({
    ok: true,
    reason: null,
    path: 'docs/fallback-smoke.md',
    requested_paths: ['docs/fallback-smoke.md']
  });
});

test('writeDeterministicCandidatePatch writes candidate.patch in sandbox and never applies repository files', () => {
  const rootDir = tmpRoot();
  const result = writeDeterministicCandidatePatch({
    rootDir,
    story: story(),
    failure_reason: 'provider_rate_limited',
    sandbox_root: '.ralph/tmp/opencode-sandbox/APR-FALLBACK',
    approval_id: 'APR-FALLBACK',
    job_id: 'JOB-FALLBACK',
    now: () => new Date('2026-05-12T10:00:00.000Z')
  });

  expect(result).toMatchObject({
    ok: true,
    reason: null,
    stage: 'deterministic_candidate_patch_fallback',
    patch_source: PATCH_SOURCE,
    provider_failure_reason: 'provider_rate_limited',
    candidate_patch_path: '.ralph/tmp/opencode-sandbox/APR-FALLBACK/candidate.patch',
    files_modified: ['.ralph/tmp/opencode-sandbox/APR-FALLBACK/candidate.patch'],
    repository_files_modified: [],
    apply_allowed: false,
    commit_allowed: false,
    push_allowed: false,
    pr_allowed: false,
    merge_allowed: false,
    deploy_allowed: false,
    migration_allowed: false,
    patch_preview: {
      ok: true,
      requires_approval: true,
      apply_allowed: false,
      patch_source: PATCH_SOURCE,
      files_touched: ['docs/fallback-smoke.md'],
      blocked_paths: []
    },
    next_action: 'preview_candidate_patch_before_apply'
  });

  const patchPath = path.join(rootDir, result.candidate_patch_path);
  expect(fs.existsSync(patchPath)).toBe(true);
  const patch = fs.readFileSync(patchPath, 'utf8');
  expect(patch).toContain('diff --git a/docs/fallback-smoke.md b/docs/fallback-smoke.md');
  expect(patch).toContain('This candidate patch was generated by Ralph deterministic fallback');
  expect(fs.existsSync(path.join(rootDir, 'docs/fallback-smoke.md'))).toBe(false);
});

test('fallback rejects ineligible runtime code unless explicitly allowed by policy', () => {
  const rootDir = tmpRoot();
  const result = writeDeterministicCandidatePatch({
    rootDir,
    story: story({ requested_paths: ['src/runtime-change.js'] }),
    failure_reason: 'provider_rate_limited',
    sandbox_root: '.ralph/tmp/opencode-sandbox/APR-FALLBACK'
  });

  expect(result).toMatchObject({
    ok: false,
    reason: 'fallback_requested_path_not_policy_allowed',
    candidate_patch_path: null,
    repository_files_modified: [],
    next_action: 'retry_or_escalate_provider_failure'
  });
  expect(fs.existsSync(path.join(rootDir, '.ralph/tmp/opencode-sandbox/APR-FALLBACK/candidate.patch'))).toBe(false);
});

test('fallback validates explicit requested path cardinality and failure reason', () => {
  const rootDir = tmpRoot();
  expect(eligibleForDeterministicFallback({
    rootDir,
    story: story({ requested_paths: ['docs/a.md', 'docs/b.md'] }),
    failure_reason: 'provider_rate_limited'
  })).toMatchObject({ ok: false, reason: 'fallback_requires_exactly_one_requested_path' });

  expect(eligibleForDeterministicFallback({
    rootDir,
    story: story(),
    failure_reason: 'syntax_error'
  })).toMatchObject({ ok: false, reason: 'fallback_failure_reason_not_allowed' });
});

test('fallback covers runtime infrastructure failures (nemoclaw/openshell timeout and not-installed)', () => {
  const rootDir = tmpRoot();
  for (const reason of [
    'nemoclaw_runtime_timeout',
    'nemoclaw_runtime_not_installed',
    'openshell_runtime_not_installed',
    'gateway_runtime_timeout'
  ]) {
    expect(eligibleForDeterministicFallback({
      rootDir,
      story: story(),
      failure_reason: reason
    })).toMatchObject({
      ok: true,
      reason: null,
      path: 'docs/fallback-smoke.md'
    });
  }
});

test('fallback refuses to synthesize existing files without provider context', () => {
  const rootDir = tmpRoot();
  fs.mkdirSync(path.join(rootDir, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(rootDir, 'docs/fallback-smoke.md'), 'existing\n', 'utf8');

  const result = writeDeterministicCandidatePatch({
    rootDir,
    story: story(),
    failure_reason: 'candidate_patch_missing',
    sandbox_root: '.ralph/tmp/opencode-sandbox/APR-FALLBACK'
  });

  expect(result).toMatchObject({
    ok: false,
    reason: 'fallback_existing_file_requires_provider_context',
    candidate_patch_path: null,
    repository_files_modified: []
  });
  expect(fs.readFileSync(path.join(rootDir, 'docs/fallback-smoke.md'), 'utf8')).toBe('existing\n');
});
